### ISSUE TITLE
Model migration problem

### ISSUE THREAD

**Issue by lizongzeng** [lanl/OpenFWI#6]
Hello,author,
Your work is great.Can I use the model trained on these data sets to process the salt body data?For example, SEG salt

Thank you very much for your attention

**Comment by hanchenwang** [comment]
Hello, thanks for your interest. Unfortunately, the pre trained model cannot be directly applied to salt models because we did not include any salt body in our dataset. I would suggest to use other dataset that contains salt body structures to retrain, at least fine-tune or transfer learning, with our networks.

**Comment by lizongzeng** [comment]
Thank you very much for your reply.Is there open source real data available to test the effectiveness of models trained in openfwi?

**Comment by hanchenwang** [comment]
Sorry, but I do not know any open source dataset that is designed for salt body imaging. You may rescale SEG salt for a preliminary test with our model. However, for fine tuning the model, I would suggest you build a few samples, for example 1000, and start from our pretrained models. For retraining, you would probably need a larger dataset designed for the task.

**Comment by hanchenwang** [comment]
You may find some open source data on SEG open data platform or the EDX platform of DOE: https://edx.netl.doe.gov/
Remember you will need to scale the data to our model capacity.

**Comment by lizongzeng** [comment]
Thank you very much for your reply. Wish you good health and success in your work.
Thank you again.
